language: android
jdk: oraclejdk8
dist: trusty

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
    - build-tools-28.0.3
    - android-28

deploy:
  provider: script
  script: ./gradlew :clean :keasy:assembleRelease :keasy:bintrayUpload
  skip_cleanup: true # to upload artifacts created during the build
  dry-run: false
  on:
    branch: master
